// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOzh2wfS-Wik0T5tvpLKHnfKpBzFY9_ns',
    appId: '1:576999197569:web:15c587142d7af6a978b680',
    messagingSenderId: '576999197569',
    projectId: 'ssh-me12',
    authDomain: 'ssh-me12.firebaseapp.com',
    storageBucket: 'ssh-me12.firebasestorage.app',
    measurementId: 'G-N2D96KHSGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUka_9odLGIKtnUHb7e-SqrbY6k2cSYM4',
    appId: '1:576999197569:android:3dcdf2c94bb6026c78b680',
    messagingSenderId: '576999197569',
    projectId: 'ssh-me12',
    storageBucket: 'ssh-me12.firebasestorage.app',
  );
}
